# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nutrients',
            new_name='Nutrient',
        ),
    ]
