# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0004_auto_20190126_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='glasses_water',
        ),
    ]
