# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0007_auto_20190126_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomrecord',
            name='present_symptoms_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
