# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0008_symptomrecord_present_symptoms_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaserecord',
            name='probable_diseases_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
