# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drug', '0009_diseaserecord_probable_diseases_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foodrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('search_query', models.CharField(blank=True, max_length=1000, null=True)),
                ('calories', models.DecimalField(decimal_places=10, max_digits=19)),
                ('fat', models.DecimalField(decimal_places=10, max_digits=19)),
                ('sugars', models.DecimalField(decimal_places=10, max_digits=19)),
                ('protein', models.DecimalField(decimal_places=10, max_digits=19)),
                ('carbohydrates', models.DecimalField(decimal_places=10, max_digits=19)),
                ('vitamina', models.DecimalField(decimal_places=10, max_digits=19)),
                ('vitaminbcomplex', models.DecimalField(decimal_places=10, max_digits=19)),
                ('vitaminc', models.DecimalField(decimal_places=10, max_digits=19)),
                ('vitamind', models.DecimalField(decimal_places=10, max_digits=19)),
                ('vitamine', models.DecimalField(decimal_places=10, max_digits=19)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='foodlist',
            name='food_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drug.Foodrecord'),
        ),
    ]
