# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0011_selfcarediary'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfcarediary',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
